steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'dialogflowFirebaseFulfillment', '--trigger-http', '--runtime', 'nodejs8', '--entry-point', 'dialogflowFirebaseFulfillment']
  dir: 'functions/autodeploy'
